export const moneyMoveQuestions = [
  { category: "Money Math", value: 100, question: "You earn $120 washing cars. You spend 25% on supplies. How much remains?", answer: "$90" },
  { category: "Money Math", value: 100, question: "A snack costs $8. GST is 12.5%. Final price?", answer: "$9" },
  { category: "Money Math", value: 100, question: "You save $15 weekly for 12 weeks. Total savings?", answer: "$180" },
  { category: "Money Math", value: 200, question: "You earn $400. Social Security and taxes take 15%. Take-home pay?", answer: "$340" },
  { category: "Money Math", value: 200, question: "You invest $250 and earn 12% profit. Final amount?", answer: "$280" },
  { category: "Money Math", value: 200, question: "A $900 laptop gets a 20% discount. New price?", answer: "$720" },
  { category: "Money Math", value: 300, question: "You buy 60 drinks for $3 each and sell them for $7 each. Profit?", answer: "$240" },
  { category: "Money Math", value: 300, question: "You save $100 monthly earning 5% annual interest. Approximate total after 1 year?", answer: "$1,260" },
  { category: "Money Math", value: 300, question: "You earn $950 monthly. Bills total $620. What percentage of income remains?", answer: "34.7%" },
  { category: "Money Math", value: 400, question: "You invest $800 and gain 15%, then lose 10% of the new total. Final amount?", answer: "$828" },
  { category: "Money Math", value: 400, question: "A business earns $2,000 revenue. Expenses are $950 and taxes are 12%. Profit?", answer: "$924" },
  { category: "Money Math", value: 400, question: "You save 30% of a $1,200 income for 18 months. Total saved?", answer: "$6,480" },
  { category: "Money Math", value: 500, question: "You invest $1,000. Gain 20%, then lose 15%, then gain 10%. Final amount?", answer: "$1,122" },
  { category: "Money Math", value: 500, question: "You buy shares at $50 each. Price rises 18%. What is the new share price?", answer: "$59" },
  { category: "Money Math", value: 500, question: "You split $2,000 into two investments: 60% earns 8%, 40% earns 15%. Total after growth?", answer: "$2,168" },
  { category: "Save Smart", value: 100, question: "You avoid spending $12 daily for 5 school days. Savings?", answer: "$60" },
  { category: "Save Smart", value: 100, question: "You save half of your $80 allowance. Amount saved?", answer: "$40" },
  { category: "Save Smart", value: 100, question: "You put $200 into savings earning 5%. Total after one year?", answer: "$210" },
  { category: "Save Smart", value: 200, question: "You want a $600 phone in 8 months. Monthly savings needed?", answer: "$75" },
  { category: "Save Smart", value: 200, question: "You save 25% of your $500 income. Monthly savings?", answer: "$125" },
  { category: "Save Smart", value: 200, question: "You spend $40 weekly on snacks. Yearly total?", answer: "$2,080" },
  { category: "Save Smart", value: 300, question: "You save $150 monthly but spend $50 monthly on takeout. How much wasted yearly?", answer: "$600" },
  { category: "Save Smart", value: 300, question: "Inflation rises 10% on your $3,000 savings buying power. Loss?", answer: "$300" },
  { category: "Save Smart", value: 300, question: "Would you rather get $500 now or $50 weekly for 15 weeks?", answer: "$50 weekly" },
  { category: "Save Smart", value: 400, question: "Your emergency fund is $1,200. A medical bill costs $350 and repairs cost $250. Remaining?", answer: "$600" },
  { category: "Save Smart", value: 400, question: "You save $200 monthly with 6% interest. Approximate total after 1 year?", answer: "$2,544" },
  { category: "Save Smart", value: 400, question: "A $1,500 laptop rises 15% in price. New cost?", answer: "$1,725" },
  { category: "Save Smart", value: 500, question: "You save $300 monthly for 2 years earning 5%. Approximate total?", answer: "$7,560" },
  { category: "Save Smart", value: 500, question: "You invest $5,000 into savings at 8%. Total after one year?", answer: "$5,400" },
  { category: "Save Smart", value: 500, question: "You save 20% of a $2,000 monthly income for 3 years. Total savings?", answer: "$14,400" },
  { category: "Hustle Mode", value: 100, question: "You sell 8 smoothies at $6 each. Revenue?", answer: "$48" },
  { category: "Hustle Mode", value: 100, question: "You buy snacks for $25 and sell them for $55. Profit?", answer: "$30" },
  { category: "Hustle Mode", value: 100, question: "You wash 5 cars at $20 each. Earnings?", answer: "$100" },
  { category: "Hustle Mode", value: 200, question: "You buy 40 juices at $2 each and sell them for $6 each. Profit?", answer: "$160" },
  { category: "Hustle Mode", value: 200, question: "You earn $450 selling pastries. Ingredients cost $140. Profit?", answer: "$310" },
  { category: "Hustle Mode", value: 200, question: "You sell 15 hoodies at $35 each. Revenue?", answer: "$525" },
  { category: "Hustle Mode", value: 300, question: "You invest $500 into your business and earn 40% profit. Final amount?", answer: "$700" },
  { category: "Hustle Mode", value: 300, question: "Your business earns $1,200 revenue and expenses are $420. Profit?", answer: "$780" },
  { category: "Hustle Mode", value: 300, question: "You split $1,500 business profit 70/30. Your share at 70%?", answer: "$1,050" },
  { category: "Hustle Mode", value: 400, question: "You sell 80 products at $15 each. Expenses are $420. Profit?", answer: "$780" },
  { category: "Hustle Mode", value: 400, question: "A hustle earns $350 weekly for 20 weeks. Total?", answer: "$7,000" },
  { category: "Hustle Mode", value: 400, question: "Inventory costs $700 and sells for $1,260. Profit percentage?", answer: "80%" },
  { category: "Hustle Mode", value: 500, question: "Your business earns $4,000 revenue. Expenses are $1,500 and taxes are 15%. Final profit?", answer: "$2,125" },
  { category: "Hustle Mode", value: 500, question: "You invest $2,000 and earn 35% profit. Final amount?", answer: "$2,700" },
  { category: "Hustle Mode", value: 500, question: "You sell 150 shirts at $30 each. Printing costs $1,400. Profit?", answer: "$3,100" },
  { category: "Real Life", value: 100, question: "Bus fare is $6 daily for 5 school days. Weekly total?", answer: "$30" },
  { category: "Real Life", value: 100, question: "Your lunch costs $15 daily for 5 days. Weekly total?", answer: "$75" },
  { category: "Real Life", value: 100, question: "You spend $25 on snacks and $18 on drinks. Total?", answer: "$43" },
  { category: "Real Life", value: 200, question: "Your phone bill is $90 and internet is $120. Total bills?", answer: "$210" },
  { category: "Real Life", value: 200, question: "You have $400 saved and spend $150 on clothes. Remaining?", answer: "$250" },
  { category: "Real Life", value: 200, question: "Your family grocery bill rises from $300 to $390. Increase amount?", answer: "$90" },
  { category: "Real Life", value: 300, question: "You save $700. A phone repair costs $180 and transportation costs $120. Remaining?", answer: "$400" },
  { category: "Real Life", value: 300, question: "You earn $1,000 monthly and save 25%. Amount saved?", answer: "$250" },
  { category: "Real Life", value: 300, question: "You borrow $800 and repay 12% extra. Total repayment?", answer: "$896" },
  { category: "Real Life", value: 400, question: "Your electricity bill rises from $220 to $310. Percentage increase?", answer: "40.9%" },
  { category: "Real Life", value: 400, question: "You spend $25 daily on lunch for 20 school days. Monthly total?", answer: "$500" },
  { category: "Real Life", value: 400, question: "A school trip costs $900. You saved $450 and earn $75 weekly. Weeks needed?", answer: "6 weeks" },
  { category: "Real Life", value: 500, question: "You earn $1,800 monthly. Rent is $550, food $350, transport $180, internet $120. Remaining?", answer: "$600" },
  { category: "Real Life", value: 500, question: "You save 20% of your $1,500 income and invest 15%. Spending money left?", answer: "$975" },
  { category: "Real Life", value: 500, question: "Your emergency fund has $2,500. Repairs cost $800 and medical costs $450. Remaining?", answer: "$1,250" },
  { category: "Money Moves", value: 100, question: "You invest $100 earning 12% return. Final amount?", answer: "$112" },
  { category: "Money Moves", value: 100, question: "A stock rises 15%. You invested $200. New value?", answer: "$230" },
  { category: "Money Moves", value: 100, question: "You lose 10% on a $500 investment. Remaining balance?", answer: "$450" },
  { category: "Money Moves", value: 200, question: "You invest $800. Gain 20%, then lose 5%. Final amount?", answer: "$912" },
  { category: "Money Moves", value: 200, question: "You split $1,000: 50% earns 8%, 50% earns 12%. Final total?", answer: "$1,100" },
  { category: "Money Moves", value: 200, question: "A crypto investment drops 25%. You started with $1,200. Remaining?", answer: "$900" },
  { category: "Money Moves", value: 300, question: "You invest $2,000. Gain 15%, then reinvest and gain another 10%. Final amount?", answer: "$2,530" },
  { category: "Money Moves", value: 300, question: "A stock rises from $40 to $52. Percentage increase?", answer: "30%" },
  { category: "Money Moves", value: 300, question: "You invest $3,000. 70% earns 10%, 30% loses 5%. Final amount?", answer: "$3,165" },
  { category: "Money Moves", value: 400, question: "You invest $5,000. Gain 18%, then lose 12%. Final amount?", answer: "$5,192" },
  { category: "Money Moves", value: 400, question: "A business grows profits from $2,500 to $3,250. Percentage growth?", answer: "30%" },
  { category: "Money Moves", value: 400, question: "You invest $4,000 into shares earning 22%. Final value?", answer: "$4,880" },
  { category: "Money Moves", value: 500, question: "You invest $10,000. Gain 25%, then lose 10%, then gain 8%. Final amount?", answer: "$12,150" },
  { category: "Money Moves", value: 500, question: "You split $8,000: 60% earns 12%, 40% earns 20%. Final total?", answer: "$9,216" },
  { category: "Money Moves", value: 500, question: "A stock falls 30%, then rises 20%. Starting from $5,000, final amount?", answer: "$4,200" }
];
